<?php

namespace Database\Seeders;

use App\Models\Tag;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class TagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tags = [
            'IA',
            'Machine Learning',
            'Technologie',
            'Innovation',
            'Santé',
            'Nutrition',
            'Bien-être',
            'Fitness',
            'Voyage',
            'Aventure',
            'Cuisine',
            'Recettes',
            'Gastronomie',
            'Éducation',
            'Apprentissage',
            'Finance',
            'Investissement',
            'Cryptomonnaies',
            'Mode',
            'Tendances',
            'Style',
            'Sports',
            'Football',
            'Basketball',
            'Tennis',
            'Culture',
            'Art',
            'Cinéma',
            'Littérature',
            'Politique',
            'Actualités',
            'Élections',
            'Environnement',
            'Écologie',
            'Climat',
            'Science',
            'Astronomie',
            'Physique',
            'Biologie',
            'Divertissement',
            'Jeux vidéo',
            'Musique',
            'Séries TV',
            'Films',
            'Immobilier',
            'Construction',
            'Location',
            'Automobile',
            'Voitures électriques',
            'Essais auto',
            'Bricolage',
            'DIY',
            'Projets maison',
            'Parenting',
            'Éducation des enfants',
            'Soins parentaux',
            'Animaux',
            'Chats',
            'Chiens',
            'Entrepreneuriat',
            'Startups',
            'Business',
            'Lifestyle',
            'Motivation',
            'Philosophie',
            'Histoire',
            'Ancien Régime',
            'Psychologie',
            'Mental',
            'Développement personnel',
            'Beauté',
            'Maquillage',
            'Coiffure',
            'Religion',
            'Spiritualité',
            'Sécurité',
            'Cybersécurité',
            'Technologie médicale',
            'Progrès médicaux',
            'Commerce',
            'E-commerce',
            'Marketing',
            'Publicité',
            'Événements',
            'Networking',
            'Blockchain',
            'Intelligence Artificielle',
            'Développement Web',
            'Applications mobiles',
            'Projets scolaires',
            'Actualités technologiques',
            'Mode durable',
            'Zéro déchet',
            'Astrophysique',
            'Voyages spatiaux',
            'Projets créatifs',
            'Renforcement musculaire',
            'Randonnée',
            'Vegan',
            'Éthique',
            'Débats',
            'Réseaux sociaux',
            'Tendances digitales',
            'Photographie',
            'Startup Nation',
            'Plantes d’intérieur',
            'Design d’intérieur',
            'Objets connectés',
        ];

        foreach ($tags as $tag) {
            Tag::create(['name' => $tag]);
        }
    }
}
